polls/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('test/', views.test, name='test'),
    path('prepare/', views.prepareUser, name='prepareUser'),
    path('<str:userMappedStr>/', include([
        path('background/', include([
            path('select/', views.selectBackground, name='selectBackground'),
            path('register/<str:bg>', views.manageBackgroundSelection, name='manageBackgroundSelection'),
        ])),
        path('questionnaire/', include([
            path('prepare/', views.prepareQuestionnaire, name='prepareQuestionnaire'),
            path('<str:performanceName>/', include([
                path('show/', views.showQuestionnaire, name='showQuestionnaire'),
                path('register/', views.manageQuestionnaireAnswer, name='manageQuestionnaireAnswer')
            ]))
        ]))
    ]))
]

testsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='homepage')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    pass

class Question(models.Model):
    text = models.TextField(primary_key=True)
    is_negative = models.BooleanField()

class Attribute(models.Model):
    name = models.CharField(max_length=30, primary_key=True)

class Performance(models.Model):
    name = models.CharField(max_length=30, primary_key=True)
    year = models.IntegerField()
    duration = models.IntegerField()
    link = models.URLField(blank=True, null=True)

class Background(models.Model):
    type = models.CharField(max_length=20, primary_key=True)

class Category(models.Model):
    name = models.CharField(max_length=30, primary_key=True)

class QuestionCategory(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    performance = models.ForeignKey(Performance, on_delete=models.CASCADE)

    value = models.IntegerField()

class Experience(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    background = models.ForeignKey(Background, on_delete=models.CASCADE)

class PerformanceCharacteristic(models.Model):
    performance = models.ForeignKey(Performance, on_delete=models.CASCADE)
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)

    value = models.CharField(max_length=30)

polls/views.py
from django.shortcuts import render
from django.db.models import Model
from django.http import HttpResponse, HttpResponseRedirect
import random
import hashlib
import string

from django.urls import reverse
from .models import *


def get_random_string_from_user(userId):
    global user_mapping_dict
    output_string = ''.join(random.SystemRandom().choice(string.ascii_letters + string.digits) for _ in range(15))
    return output_string

def add_mapping(userStr, userId):
    global user_mapping_dict
    user_mapping_dict[userStr] = userId
    print(user_mapping_dict)

def get_user_from_string(str):
    global user_mapping_dict
    return user_mapping_dict[str]

def remove_user_mapping(str):
    global user_mapping_dict
    user_mapping_dict.pop(str, None)

# se si resetta il server, viene svuotato
# un utente potrebbe non essere in grado di
# completare il questionario se accadesse durante
# la compilazione
user_mapping_dict = {
}

# codifica sha dell'id dell'user
def get_sha():
    pass


# Create your views here.

def test(request):
    return render(
        request,
        'polls/test.html',
        context={
            'performance':Performance.objects.get_or_create(
                name='testPerformance',
                year=2022,
                duration=120,
                link="https://www.youtube.com/embed/O91DT1pR1ew"
            )[0],
            'musicGenre':'test1',
            "AITechnique":'test2',
            'categories':Category.objects.all().order_by('?'),
            'likertValues':range(1,6),
            'userMappedStr':'loljknoidea'
        }
    )

# gestisce la homepage del sito
def homepage(request):
    # conta se sono presenti delle performance
    count = Performance.objects.exclude(link__isnull=True).count()

    return render(
        request,
        'polls/homepage.html',
        context={
            'count':count,
        }
    )

# dopo aver cliccato su 'Avvia Questionario' viene generato
# un utente e la sua stringa identificativa
def prepareUser(request):
    #user = get_sha()
    user = User.objects.create()

    userMappedStr = get_random_string_from_user(user.pk)
    add_mapping(userMappedStr, user.pk)

    bgs = Background.objects.all()
    count = bgs.count()

    # non ci sono background da scegliere
    if(count==0):
        return HttpResponseRedirect(reverse('prepareQuestionnaire', args=[userMappedStr]))
    # esiste un solo background, viene fatta in automatico l'associazione
    elif(count==1):
        return HttpResponseRedirect(reverse('manageBackgroundSelection', args=[userMappedStr, bgs[0].type]))
    else:
        return HttpResponseRedirect(reverse('selectBackground', args=[userMappedStr]))

# dopo la creazione dell'utente, verrà mostrata una pagina in cui 
# verrà chiesto di scegliere il proprio background
def selectBackground(request, userMappedStr):
    return render(
        request,
        'polls/selectBackground.html',
        context={
            'backgrounds':Background.objects.all(),
            'userMappedStr':userMappedStr
        }
    )

# inserisce la relazione tra user e background nel database
def manageBackgroundSelection(request, userMappedStr, bg):
    background = Background.objects.get(pk=bg)
    userId = get_user_from_string(userMappedStr)
    user = User.objects.get(pk=userId)
    
    Experience.objects.create(background=background, user=user)
    
    return HttpResponseRedirect(reverse('prepareQuestionnaire', args=[userMappedStr]))

# dopo aver ultimato la creazione dell'utente, viene
# scelta una performance casuale da cui iniziare il questionario
# è assicurato che ci sia almeno una performance, altrimenti non
# si potrebbe arrivare a questo URL
def prepareQuestionnaire(request, userMappedStr):
    startingPerformance = Performance.objects.exclude(link__isnull=True).order_by('?').first().name

    return HttpResponseRedirect(reverse('showQuestionnaire', args=[userMappedStr, startingPerformance]))

# mostra la pagina del questionario
def showQuestionnaire(request, userMappedStr, performanceName):
    performance = Performance.objects.get(pk=performanceName)
    
    try:
        musicGenre = performance.performancecharacteristic_set.get(attribute='musicGenre').value
    except PerformanceCharacteristic.DoesNotExist:
        musicGenre = "Not defined"
    
    try:
        AITechnique = performance.performancecharacteristic_set.get(attribute='AItechnique').value
    except PerformanceCharacteristic.DoesNotExist:
        AITechnique = "Not defined"
    
    return render(
        request,
        'polls/showQuestionnaire.html',
        context={
            'performance':performance,
            'musicGenre':musicGenre,
            "AITechnique":AITechnique,
            'categories':Category.objects.all().order_by('?'),
            'likertValues':range(1,6),
            'userMappedStr':userMappedStr
        }
    )


def manageQuestionnaireAnswer(request, userMappedStr, performanceName):
    performance = Performance.objects.get(pk=performanceName)
    userId = get_user_from_string(userMappedStr)
    user = User.objects.get(pk=userId)

    if request.method == 'POST':
        # legge i dati inviati tramite POST
        for question in Question.objects.all():
            answer = request.POST.get(question.text)

            if answer != None:
                Answer.objects.create(
                    user=user,
                    performance=performance,
                    question=question,
                    value=answer
                )

        # qui si constrolla se l'utente ha finito di compilare il questionario
        performancesViewedByTheUser = user.answer_set.values_list('performance', flat=True).distinct()  # ritorna un elenco di PK, non oggetti

        # l'utente ha fornito una risposta per tutte le performance per cui è disponibile il video
        if performancesViewedByTheUser.count() == Performance.objects.exclude(link__isnull=True).count():
            remove_user_mapping(userMappedStr)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            # rimanda l'utente ad un nuovo questionario
            nextPerformance = Performance.objects.exclude(pk__in=performancesViewedByTheUser).order_by('?').first().name
            return HttpResponseRedirect(reverse('showQuestionnaire', args=[userMappedStr, nextPerformance]))

polls/templates/polls/base.html
<html>
    <head>
        <!-- INSERT HEAD INFO HERE -->
        <title>
            {% block title %}
                children template should override this block
            {% endblock title %}
        </title>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    </head>

    <body style="height:100vh">
        <div class="container-fluid fixed-top" style="height:100%">
            <div class="row bg-warning" style="height:10%">
                <div class="container-fluid" style="height:100%">
                    {% block header %}
                        <div id="header" style="height:100%">
                            define base header here
                        </div>
                    {% endblock header %}
                </div>
            </div>


            <div class="row" style="height:80%">
                <div class="container-fluid" style="height:100%">
                    {% block content %}
                        <div id="content" style="height:100%">
                            children templates should override this block
                        </div>
                    {% endblock content %}
                </div>
            </div>


            <div class="row bg-warning fixed-bottom" style="height:10%">
                <div class="container-fluid" style="height:100%">
                    {% block footer %}
                        <div id="footer" style="height:100%">
                            define base footer here
                        </div>
                    {% endblock footer %}
                </div>
            </div>
        </div>

        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    </body>
</html>

polls/templates/polls/homepage.html
{% extends "polls/base.html" %}

{% block title %}
    Homepage
{% endblock title %}

{% block content %}
    <h1>Homepage</h1>

    <div class="text-center" style="height:100%">
        {% if count > 0 %}
            <a class="btn btn-primary text-center"  href="{% url 'prepareUser' %}">Start questionnaire</a>
        {% else %}
            <a class="btn btn-secondary text-center disabled" href="#">Start questionnaire</a>
            <p class="text-cented text-secondary">(No performance available)</p>
        {% endif %}
    </div>
    
{% endblock content %}

polls/templates/polls/selectBackground.html
{% extends "polls/base.html" %}
{% load static %}

{% block title %}
    Background selection
{% endblock title %}

{% block content %}
    <div class="row" style="height:10%">
        <h1>Scelta background</h1>
    </div>

    <div class="row mx-5 pb-5" style="height:90%">
        {% for bg in backgrounds %}
            <div class="col-sm-4 px-5" style="height:100%">
                <div class="card border border-4 border-primary" style="height:100%">
                    <img class="card-img-top" style="object-fit:cover" height="100%" src="{% static 'polls/images/'|add:bg.type|add:'_bg.jpg' %}" alt="{{bg.type}}">
                    <div class="card-footer bg-primary text-white text-center">{{bg.type|upper}}</div>
                    <a href="{% url 'manageBackgroundSelection' userMappedStr bg.type %}" class="stretched-link"></a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

polls/templates/polls/showQuestionnaire.html
{% extends "polls/base.html" %}

{% block title %}
    Questionnaire
{% endblock title %}

{% block content %}
    <style>
        .my_td {
            border:none
        }
    </style>

    <div style="height: 10%;">
        <h1>Questionario su {{performance.name}}</h1>
    </div>

    <div style="width:45%; height: 90%; float:left; word-break: break-all;">
        <iframe style="display:block;margin:auto" width="80%" height="65%" src="{{performance.link}}" title="{{performance.name}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="m-3">
            <table class="table table-responsive">
                <tbody>
                    <tr>
                        <td><b>NAME</b></td>
                        <td>{{performance.name}}</td>
                    </tr>
                    <tr>
                        <td><b>YEAR</b></td>
                        <td>{{performance.year}}</td>
                    </tr>
                    <tr>
                        <td><b>MUSIC GENRE</b></td>
                        <td>{{musicGenre}}</td>
                    </tr>
                    <tr>
                        <td><b>AI TECHNIQUE</b></td>
                        <td>{{AITechnique}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div style="overflow-y:scroll; width:55%; height:90%; float:right;  word-break: break-all">
        <form action="{% url 'manageQuestionnaireAnswer' userMappedStr performance.name %}" method="post">
            {% csrf_token %}
            {% for category in categories %}
                <div class="mx-2">
                    <h3><b>{{category.name}}</b></h3>
                    {% for entry in category.questioncategory_set.all %}
                        <p>{{entry.question.text}}</p>
                        <table class="table text-center text-secondary table-responsive">
                               <tbody>
                                    <tr>
                                        <td class="my_td">Strongly Disagree</td>
                                        <td class="my_td"><input class="form-check-input" style="height: 25px; width: 25px;" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_1" value="1" required></td>
                                        <td class="my_td"><input class="form-check-input" style="height: 20px; width: 20px; margin-top: 5px;" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_2" value="2" required></td>
                                        <td class="my_td"><input class="form-check-input" style="height: 15px; width: 15px; margin-top: 10px" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_3" value="3" required></td>
                                        <td class="my_td"><input class="form-check-input" style="height: 20px; width: 20px; margin-top: 5px" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_4" value="4" required></td>
                                        <td class="my_td"><input class="form-check-input" style="height: 25px; width: 25px;" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_5" value="5" required></td>
                                        <td class="my_td">Strongly Agree</td>
                                    </tr>
                               </tbody>
                            </table> 
                    {% endfor %}
                </div>
                <br>
                <hr style="width: 90%;">
                <br>
            {% endfor %}
            <div class="text-center">
                <input class="btn btn-primary mx-2" type="submit" value="Avanti">
                <input class="btn btn-primary mx-2" type="reset" value="Pulisci risposte">
            </div>
        </form>
    </div>
{% endblock content %}

polls/templates/polls/test.html
{% extends "polls/base.html" %}

{% block title %}
    Questionnaire
{% endblock title %}

{% block content %}
    <style>
        .my_td {
            border:none
        }
    </style>

    <div style="height: 10%;">
        <h1>Questionario su {{performance.name}}</h1>
    </div>

    <div style="width:45%; height: 90%; float:left; word-break: break-all;">
        <iframe style="display:block;margin:auto" width="80%" height="65%" src="{{performance.link}}" title="{{performance.name}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="m-3">
            <table class="table table-responsive">
                <tbody>
                    <tr>
                        <td><b>NAME</b></td>
                        <td>{{performance.name}}</td>
                    </tr>
                    <tr>
                        <td><b>YEAR</b></td>
                        <td>{{performance.year}}</td>
                    </tr>
                    <tr>
                        <td><b>MUSIC GENRE</b></td>
                        <td>{{musicGenre}}</td>
                    </tr>
                    <tr>
                        <td><b>AI TECHNIQUE</b></td>
                        <td>{{AITechnique}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div style="overflow-y:scroll; width:55%; height:90%; float:right;  word-break: break-all">
        <form action="{% url 'manageQuestionnaireAnswer' userMappedStr performance.name %}" method="post">
            {% csrf_token %}
            {% for category in categories %}
                <div class="mx-2">
                    <h3><b>{{category.name}}</b></h3>
                    {% for entry in category.questioncategory_set.all %}
                        <p>{{entry.question.text}}</p>
                        <table class="table text-center text-secondary table-responsive">
                               <tbody>
                                    <tr>
                                        <td class="my_td">Strongly Disagree</td>
                                        <td class="my_td"><input class="form-check-input" style="height: 25px; width: 25px;" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_1" value="1" required></td>
                                        <td class="my_td"><input class="form-check-input" style="height: 20px; width: 20px; margin-top: 5px;" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_2" value="2" required></td>
                                        <td class="my_td"><input class="form-check-input" style="height: 15px; width: 15px; margin-top: 10px" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_3" value="3" required></td>
                                        <td class="my_td"><input class="form-check-input" style="height: 20px; width: 20px; margin-top: 5px" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_4" value="4" required></td>
                                        <td class="my_td"><input class="form-check-input" style="height: 25px; width: 25px;" type="radio" name="{{entry.question.text}}" id="{{entry.question.text}}_5" value="5" required></td>
                                        <td class="my_td">Strongly Agree</td>
                                    </tr>
                               </tbody>
                            </table> 
                    {% endfor %}
                </div>
                <br>
                <hr style="width: 90%;">
                <br>
            {% endfor %}
            <div class="text-center">
                <input class="btn btn-primary mx-2" type="submit" value="Avanti">
                <input class="btn btn-primary mx-2" type="reset" value="Pulisci risposte">
            </div>
        </form>
    </div>
{% endblock content %}